apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-pyapp
  labels:
    app: web-pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-pyapp
  template:
    metadata:
      labels:
        app: web-pyapp
    spec:
      containers:
      - name: web-pyapp
        image: acraksapps.azurecr.io/web/pyapp:0.0.2
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-pyapp-service
spec:
  selector:
    app: web-pyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
