apiVersion: v1
kind: Namespace
metadata:
  name: web-dev

---
# storage key secret
apiVersion: v1
kind: Secret
metadata:
  name: az-storage-key
  namespace: web-dev
data:
  azurestorageaccountname: strgaksdev
  azurestorageaccountkey: ""

---
# storage class for dynamic azure file creation
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-azurefile
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - mfsymlinks
 - cache=strict
 - actimeo=30
 - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks
parameters:
  skuName: Standard_LRS
  storageAccount: strgaksdev
  storageEndpointSuffix: core.windows.net
  secretName: az-storage-key
---

# PV claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sc-azurefile
  resources:
    requests:
      storage: 100Gi

---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-pyapp
  namespace: web-dev
  labels:
    app: web-pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-pyapp
  template:
    metadata:
      labels:
        app: web-pyapp
    spec:
      containers:
      - name: web-pyapp
        image: acraksapps.azurecr.io/web/pyapp:0.0.2
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        volumeMounts:
            - name: volume-azurefile
              mountPath: /mnt/azure
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      
      volumes:
        - name: volume-azurefile
          persistentVolumeClaim:
            claimName: pvc-azurefile
---
apiVersion: v1
kind: Service
metadata:
  name: web-pyapp-service
  namespace: "web-dev"
spec:
  selector:
    app: web-pyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
