# service account for workload identity
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "client id"
  name: "aks-serviceaccount-workload-identity"
  namespace: "web-dev"