apiVersion: v1
kind: Service
metadata:
  name: web-pyapp-service
  namespace: {{  .Values.namespace  }}
spec:
  selector:
    {{- range $key, $val := .Values.service.selector }}
        {{ $key }}: {{ $val }}
    {{- end }}
  ports:
    - protocol: TCP
      port: {{  .Values.service.port }}
      targetPort: {{  .Values.service.targetPort }}
  type: ClusterIP