# service account for workload identity
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "client id"
  name: "sa-az-workload-identity"
  namespace: "web-dev"