# storage class for dynamic azure file creation
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.file.name  }}
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - mfsymlinks
 - cache=strict
 - actimeo=30
 - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks
parameters:
  skuName: {{  .Values.storage.file.skuName  }}
  # secretName: az-secret-storage # secret created via cmdline
  shareName: {{  .Values.storage.file.shareName }}